#!/usr/bin/env python3
"""Generate src/pdf/pdf_accent_compose.inc from the Unicode Character Database
(through Python's unicodedata; its version is written into the output).

Usage:
  gen_accent_compose.py > src/pdf/pdf_accent_compose.inc

Two tables:
  * kSpacingAccents: spacing accent -> combining mark. Taken from every code
    point whose compatibility decomposition is a space and one combining mark
    (U+00A8 diaeresis, U+02DC small tilde, ...), plus the modifier letters
    and the ASCII grave that fonts name as accents but Unicode does not
    decompose (U+02C6 circumflex, U+02C7 caron, U+02C9 macron, U+02CA acute,
    U+02CB grave, U+0060 grave). ASCII ^ and ~ are left out: in text they
    are symbols far more often than accents.
  * kAccentCompose: (combining mark, base letter) -> the precomposed letter,
    for every letter of the Basic Multilingual Plane whose canonical
    composition with one of those marks is a single code point.
"""
import sys
import unicodedata

MODIFIERS = {0x2C6: 0x302, 0x2C7: 0x30C, 0x2C9: 0x304, 0x2CA: 0x301, 0x2CB: 0x300, 0x60: 0x300}


def spacing_accents():
    out = dict(MODIFIERS)
    for cp in range(0x20, 0x10000):
        d = unicodedata.decomposition(chr(cp)).split()
        if len(d) == 3 and d[0] == "<compat>" and d[1] == "0020":
            mark = int(d[2], 16)
            if unicodedata.combining(chr(mark)):
                out[cp] = mark
    return dict(sorted(out.items()))


def compositions(marks):
    rows = []
    for mark in sorted(set(marks)):
        for cp in range(0x20, 0x10000):
            if not unicodedata.category(chr(cp)).startswith("L"):
                continue
            c = unicodedata.normalize("NFC", chr(cp) + chr(mark))
            if len(c) == 1:
                rows.append((mark, cp, ord(c)))
    return rows


def main():
    acc = spacing_accents()
    rows = compositions(acc.values())
    w = sys.stdout.write
    w("// Generated by tools/gen_accent_compose.py -- do not edit by hand.\n")
    w("// Unicode %s (Python unicodedata).\n\n" % unicodedata.unidata_version)
    w("struct SpacingAccent { uint16_t spacing, mark; };\n")
    w("static const SpacingAccent kSpacingAccents[] = {\n")
    for s, m in acc.items():
        w("    {0x%04X, 0x%04X},\n" % (s, m))
    w("};\n\n")
    w("// Sorted by (mark, base).\n")
    w("struct AccentCompose { uint16_t mark, base, composed; };\n")
    w("static const AccentCompose kAccentCompose[] = {\n")
    for m, b, c in rows:
        w("    {0x%04X, 0x%04X, 0x%04X},\n" % (m, b, c))
    w("};\n")


if __name__ == "__main__":
    main()
