#!/usr/bin/env python3
"""Generate src/pdf/pdf_base14_data.inc from the Adobe Core14 AFM files.

Inputs (none of them are committed; fetch them once to regenerate):
  * The 14 Core14 AFM files and their readme.txt (Adobe, "Core14_AFMs"),
    e.g. matplotlib/mpl-data/fonts/pdfcorefonts/ ships an unmodified copy.
  * glyphlist.txt and zapfdingbats.txt -- the Adobe Glyph List
    (https://github.com/adobe-type-tools/agl-aglfn, BSD-3-Clause).
  * symbol.txt and zdingbat.txt -- Adobe Symbol / Zapf Dingbats encoding to
    Unicode (https://www.unicode.org/Public/MAPPINGS/VENDORS/ADOBE/).

Usage:
  gen_base14_metrics.py AFM_DIR AGL_DIR UNICODE_MAPPINGS_DIR > src/pdf/pdf_base14_data.inc

Only the advance widths (WX), glyph names and the font's built-in code are
extracted; nothing else from the AFM files is used.
"""
import os
import sys

LATIN = ["Courier", "Courier-Bold", "Courier-BoldOblique", "Courier-Oblique",
         "Helvetica", "Helvetica-Bold", "Helvetica-BoldOblique", "Helvetica-Oblique",
         "Times-Roman", "Times-Bold", "Times-BoldItalic", "Times-Italic"]
SYMBOLIC = ["Symbol", "ZapfDingbats"]


def read_afm(path):
    glyphs = []  # (name, code, wx)
    in_metrics = False
    with open(path, encoding="latin-1") as f:
        for line in f:
            line = line.strip()
            if line.startswith("StartCharMetrics"):
                in_metrics = True
                continue
            if line.startswith("EndCharMetrics"):
                break
            if not in_metrics or not line:
                continue
            fields = {}
            for part in line.split(";"):
                part = part.strip().split()
                if len(part) >= 2:
                    fields[part[0]] = part[1]
            glyphs.append((fields["N"], int(fields["C"]), int(fields["WX"])))
    return glyphs


def read_agl(path):
    m = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("#") or ";" not in line:
                continue
            name, cps = line.strip().split(";")
            m.setdefault(name, int(cps.split()[0], 16))
    return m


def read_vendor_map(path):
    """code -> list of Unicode values, in file order."""
    m = {}
    with open(path, encoding="latin-1") as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            cols = line.split("\t")
            m.setdefault(int(cols[1], 16), []).append(int(cols[0], 16))
    return m


def is_pua(u):
    return 0xE000 <= u <= 0xF8FF


def symbol_unicode(cands):
    # The Symbol font is a Greek/math face: prefer the Greek-block reading of
    # a doubly mapped glyph (Omega, Delta, mu) over the compatibility one.
    for u in cands:
        if 0x0370 <= u <= 0x03FF:
            return u
    for u in cands:
        if not is_pua(u):
            return u
    return cands[0]


def main():
    afm_dir, agl_dir, map_dir = sys.argv[1:4]
    agl = read_agl(os.path.join(agl_dir, "glyphlist.txt"))
    agl_zapf = read_agl(os.path.join(agl_dir, "zapfdingbats.txt"))
    sym_map = read_vendor_map(os.path.join(map_dir, "symbol.txt"))
    zapf_map = read_vendor_map(os.path.join(map_dir, "zdingbat.txt"))
    readme = open(os.path.join(afm_dir, "readme.txt"), encoding="latin-1").read()
    lic = readme[readme.index("This file and the 14"):].strip()

    afm = {n: read_afm(os.path.join(afm_dir, n + ".afm")) for n in LATIN + SYMBOLIC}

    # The twelve Latin faces share one glyph set (ExtendedRoman, 315 glyphs).
    latin_names = sorted(g[0] for g in afm["Helvetica"])
    for n in LATIN:
        assert sorted(g[0] for g in afm[n]) == latin_names, n

    out = []
    w = out.append
    w("// Generated by tools/gen_base14_metrics.py -- do not edit by hand.")
    w("//")
    w("// Advance widths of the PDF standard 14 fonts, taken from Adobe's Core14")
    w("// AFM files (Core14_AFMs, AFM version 4.1, Adobe Systems Incorporated).")
    w("// Glyph-to-Unicode values come from the Adobe Glyph List (glyphlist.txt,")
    w("// zapfdingbats.txt; BSD-3-Clause, Copyright 2002-2019 Adobe) and the Adobe")
    w("// Symbol / Zapf Dingbats to Unicode tables published by Unicode, Inc.")
    w("// Only the glyph names, built-in codes and WX values are reproduced.")
    w("//")
    w("// Copyright notices of the AFM files, retained as their license requires:")
    notices = set()
    for n in LATIN + SYMBOLIC:
        with open(os.path.join(afm_dir, n + ".afm"), encoding="latin-1") as f:
            for line in f:
                if line.startswith("Notice "):
                    notices.add(" ".join(line[len("Notice "):].split()))
    for notice in sorted(notices):
        w("//   " + notice)
    w("//")
    w("// The AFM license (readme.txt of Core14_AFMs) reads:")
    w("//")
    for line in lic.splitlines():
        w(("// " + line.rstrip()).rstrip())
    w("//")
    w("// The Adobe Glyph List license reads:")
    w("//")
    with open(os.path.join(agl_dir, "glyphlist.txt"), encoding="utf-8") as f:
        head = []
        for line in f:
            if not line.startswith("#"):
                break
            head.append(line[1:].rstrip())
    rule = [i for i, line in enumerate(head) if line.strip().startswith("-----")]
    for line in head[rule[0] + 1:rule[1]]:
        w(("//" + line).rstrip())
    w("")

    def emit_glyphs(ident, rows):
        # rows: (name, unicode, code) sorted by name
        w(f"static const Base14Glyph {ident}[] = {{")
        for name, u, code in rows:
            w(f'    {{"{name}", 0x{u:04X}, {code}}},')
        w("};")

    def emit_unicode_index(ident, rows):
        idx = sorted(range(len(rows)), key=lambda i: (rows[i][1], rows[i][0]))
        seen = set()
        keep = []
        for i in idx:
            u = rows[i][1]
            if u in seen:  # first (alphabetically) glyph wins for a shared value
                continue
            seen.add(u)
            keep.append(i)
        w(f"static const uint16_t {ident}[] = {{")
        for k in range(0, len(keep), 16):
            w("    " + ", ".join(str(i) for i in keep[k:k + 16]) + ",")
        w("};")
        return len(keep)

    def emit_widths(ident, names, glyphs):
        by = {g[0]: g[2] for g in glyphs}
        w(f"static const uint16_t {ident}[] = {{")
        vals = [by[n] for n in names]
        for k in range(0, len(vals), 16):
            w("    " + ", ".join(str(v) for v in vals[k:k + 16]) + ",")
        w("};")

    # Latin
    std_code = {g[0]: g[1] for g in afm["Helvetica"]}
    latin_rows = []
    for n in latin_names:
        assert n in agl, n
        code = std_code[n]
        latin_rows.append((n, agl[n], code if code >= 0 else 0))
    emit_glyphs("kLatinGlyphs", latin_rows)
    n_latin_u = emit_unicode_index("kLatinByUnicode", latin_rows)
    for n in LATIN:
        emit_widths("kW_" + n.replace("-", "_"), latin_names, afm[n])

    # Symbolic faces: Unicode from the vendor table by built-in code.
    sym_rows = {}
    for n, table, fallback in (("Symbol", sym_map, agl), ("ZapfDingbats", zapf_map, agl_zapf)):
        rows = []
        for name, code, wx in sorted(afm[n]):
            if code >= 0 and code in table:
                u = symbol_unicode(table[code]) if n == "Symbol" else table[code][0]
            else:
                u = fallback.get(name, 0)
            rows.append((name, u, code if code >= 0 else 0))
        sym_rows[n] = rows
        ident = n.replace("-", "_")
        emit_glyphs(f"k{ident}Glyphs", rows)
        sym_rows[n + "_u"] = emit_unicode_index(f"k{ident}ByUnicode", rows)
        emit_widths("kW_" + ident, [r[0] for r in rows], afm[n])

    w("")
    w("static const Base14Font kBase14Fonts[] = {")
    for n in LATIN:
        ident = "kW_" + n.replace("-", "_")
        w(f'    {{"{n}", false, kLatinGlyphs, {ident}, {len(latin_rows)}, kLatinByUnicode, {n_latin_u}}},')
    for n in SYMBOLIC:
        ident = n.replace("-", "_")
        w(f'    {{"{n}", true, k{ident}Glyphs, kW_{ident}, {len(sym_rows[n])}, '
          f'k{ident}ByUnicode, {sym_rows[n + "_u"]}}},')
    w("};")
    print("\n".join(out))


if __name__ == "__main__":
    main()
