#!/usr/bin/env python3
"""Generate src/pdf/pdf_cid_unicode_data.inc from Adobe's CID-to-Unicode CMaps.

Inputs (not committed; fetch them once to regenerate):
  * Adobe-GB1-UCS2, Adobe-CNS1-UCS2, Adobe-Japan1-UCS2, Adobe-Korea1-UCS2
    from https://github.com/adobe-type-tools/mapping-resources-pdf
    (pdf2unicode/, BSD-3-Clause, Copyright 1990-2019 Adobe).

Usage:
  gen_cid_unicode.py CMAP_DIR > src/pdf/pdf_cid_unicode_data.inc

Each collection becomes an array indexed by CID holding the first Unicode
scalar of the CID's mapping (0 = unmapped). Values outside the BMP are kept
in a short sorted side table, so the main arrays stay 16-bit.
"""
import os
import re
import sys

ORDERINGS = ["GB1", "CNS1", "Japan1", "Korea1"]


def parse(path):
    text = open(path, encoding="latin-1").read()
    version = re.search(r"%%Version:\s*(\S+)", text).group(1)
    raw = {}
    for blk in re.findall(r"beginbfchar(.*?)endbfchar", text, re.S):
        for a, b in re.findall(r"<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>", blk):
            raw[int(a, 16)] = [int(b[i:i + 4], 16) for i in range(0, len(b), 4)]
    for blk in re.findall(r"beginbfrange(.*?)endbfrange", text, re.S):
        for a, b, c in re.findall(r"<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>", blk):
            lo, hi, u = int(a, 16), int(b, 16), int(c, 16)
            for cid in range(lo, hi + 1):
                raw[cid] = [u + cid - lo]
    out = {}
    for cid, units in raw.items():
        u = units[0]
        if 0xD800 <= u < 0xDC00 and len(units) > 1:
            u = 0x10000 + ((u - 0xD800) << 10) + (units[1] - 0xDC00)
        out[cid] = u
    return version, out


def main():
    src = sys.argv[1]
    w = sys.stdout.write
    w("// Generated by tools/gen_cid_unicode.py -- do not edit by hand.\n//\n")
    w("// CID-to-Unicode mappings of the Adobe character collections, from Adobe's\n")
    w("// mapping-resources-pdf (pdf2unicode/Adobe-*-UCS2):\n")
    tables = []
    for o in ORDERINGS:
        version, m = parse(os.path.join(src, f"Adobe-{o}-UCS2"))
        tables.append((o, version, m))
        w(f"//   Adobe-{o}-UCS2 version {version}, {len(m)} CIDs\n")
    w("//\n// Copyright 1990-2019 Adobe. All rights reserved.\n//\n")
    w("// Redistribution and use in source and binary forms, with or without\n"
      "// modification, are permitted provided that the following conditions are met:\n"
      "// Redistributions of source code must retain the above copyright notice,\n"
      "// this list of conditions and the following disclaimer. Redistributions in\n"
      "// binary form must reproduce the above copyright notice, this list of\n"
      "// conditions and the following disclaimer in the documentation and/or other\n"
      "// materials provided with the distribution. Neither the name of Adobe nor the\n"
      "// names of its contributors may be used to endorse or promote products\n"
      "// derived from this software without specific prior written permission.\n"
      "// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"\n"
      "// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n"
      "// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\n"
      "// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE\n"
      "// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR\n"
      "// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF\n"
      "// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS\n"
      "// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN\n"
      "// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\n"
      "// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n"
      "// POSSIBILITY OF SUCH DAMAGE.\n\n")
    for o, _, m in tables:
        n = max(m) + 1
        w(f"static const uint16_t k{o}[{n}] = {{\n")
        vals = [m.get(c, 0) if m.get(c, 0) < 0x10000 else 0 for c in range(n)]
        for i in range(0, n, 16):
            w("    " + ",".join(str(v) for v in vals[i:i + 16]) + ",\n")
        w("};\n")
        astral = sorted((c, u) for c, u in m.items() if u >= 0x10000)
        w(f"static const CidAstral k{o}Astral[] = {{\n")
        for c, u in astral:
            w(f"    {{{c}, 0x{u:X}}},\n")
        if not astral:
            w("    {0, 0},\n")
        w("};\n")
    w("\nstatic const CidCollection kCollections[] = {\n")
    for o, _, m in tables:
        n_astral = sum(1 for u in m.values() if u >= 0x10000)
        w(f"    {{\"{o}\", k{o}, sizeof(k{o}) / sizeof(k{o}[0]), k{o}Astral, {n_astral}}},\n")
    w("};\n")


if __name__ == "__main__":
    main()
